services:
  db:
    image: postgres:16-alpine
    container_name: mornut_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mornut
      POSTGRES_PASSWORD: mornut
      POSTGRES_DB: mornut
    ports:
      - "5433:5432"
    volumes:
      - mornut_pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mornut_pgdata:
